# Generated by Django 2.2.7 on 2019-11-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('TEMPORARY', 'TEMPORARY')], max_length=10)),
            ],
        ),
    ]
