# Generated by Django 2.2.7 on 2019-11-23 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_hours', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('department_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Department')),
                ('employee_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
            ],
        ),
    ]
